package main

import (
	"fmt"
	"go/format"
	"os"
	"strings"
)

type genFile struct {
	name   string
	source []byte
}

func emit(r *ir, pin, packageName string) []genFile {
	return []genFile{
		{"types_gen.go", emitTypes(r, pin, packageName)},
		{"methods_gen.go", emitMethods(r, pin, packageName)},
		{"parity_gen_test.go", emitParity(r, pin, packageName)},
	}
}

func formatSrc(src string) []byte {
	out, err := format.Source([]byte(src))
	if err != nil {
		// Rendering bugs must fail the build loudly, with the source
		// preserved for inspection.
		_ = os.WriteFile("/tmp/acpgen-broken.go", []byte(src), 0o644)
		panic(fmt.Sprintf("generated invalid Go: %v (source in /tmp/acpgen-broken.go)", err))
	}
	return out
}

func header(pin, what string) string {
	return fmt.Sprintf("// Code generated by acpgen from ACP JSON Schema release %s (%s). DO NOT EDIT.\n\n", pin, what)
}

func writeDoc(b *strings.Builder, indent, doc string) {
	if doc == "" {
		return
	}
	const maxLines = 12
	lines := strings.Split(strings.ReplaceAll(doc, "\r", ""), "\n")
	wrote := 0
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		line = stripMarkdown(line)
		if line == "" {
			continue
		}
		if wrote == maxLines {
			b.WriteString(indent + "// …\n")
			return
		}
		b.WriteString(indent + "// " + line + "\n")
		wrote++
	}
}

// stripMarkdown removes inline markup that reads poorly in godoc.
func stripMarkdown(s string) string {
	// [text](url) → text
	for {
		open := strings.Index(s, "](")
		if open < 0 {
			break
		}
		start := strings.LastIndex(s[:open], "[")
		end := strings.Index(s[open:], ")")
		if start < 0 || end < 0 {
			break
		}
		end += open
		s = s[:start] + s[start+1:open] + s[end+1:]
	}
	s = strings.ReplaceAll(s, "`", "")
	s = strings.ReplaceAll(s, "**", "")
	return s
}

func (f field) isContainer() bool {
	return strings.HasPrefix(f.GoType, "[]") || strings.HasPrefix(f.GoType, "map[") ||
		f.GoType == "Meta" || f.GoType == "json.RawMessage" || f.GoType == "any"
}

func (f field) pointer() bool {
	return !f.Nullable && !f.Required && !f.isContainer()
}

func (f field) goDecl() string {
	typ := f.GoType
	if f.Nullable {
		typ = "Nullable[" + typ + "]"
	} else if f.pointer() {
		typ = "*" + typ
	}
	omit := ""
	if !f.Required {
		if f.Nullable {
			omit = ",omitzero"
		} else {
			omit = ",omitempty"
		}
	}
	return fmt.Sprintf("%s %s `json:\"%s%s\"`", f.GoName, typ, f.JSONName, omit)
}

func emitNullable(b *strings.Builder) {
	b.WriteString(`// Nullable preserves the difference between an omitted field, an explicit
// JSON null, and a concrete value. Set controls wire presence; Null requests
// an explicit null; Value carries the concrete payload when Null is false.
type Nullable[T any] struct {
	Set   bool
	Null  bool
	Value T
}

func (v Nullable[T]) MarshalJSON() ([]byte, error) {
	if !v.Set || v.Null {
		return []byte("null"), nil
	}
	return json.Marshal(v.Value)
}

func (v *Nullable[T]) UnmarshalJSON(data []byte) error {
	v.Set = true
	if string(data) == "null" {
		v.Null = true
		var zero T
		v.Value = zero
		return nil
	}
	return json.Unmarshal(data, &v.Value)
}

func (v Nullable[T]) IsZero() bool { return !v.Set }

`)
}

func emitTypes(r *ir, pin, packageName string) []byte {
	var b strings.Builder
	b.WriteString(header(pin, "wire types"))
	b.WriteString("package " + packageName + "\n\nimport (\n\t\"encoding/json\"\n\t\"fmt\"\n)\n\n")
	b.WriteString("// Meta is the reserved _meta channel for extension data.\ntype Meta map[string]any\n\n")
	if r.PreserveNull {
		emitNullable(&b)
	}

	for _, td := range r.Defs {
		writeDoc(&b, "", td.Doc)
		switch td.Kind {
		case kindNewtype:
			fmt.Fprintf(&b, "type %s %s\n\n", td.Name, td.Base)

		case kindEnum:
			fmt.Fprintf(&b, "type %s %s\n\n", td.Name, td.Base)
			if len(td.Variants) > 0 {
				b.WriteString("const (\n")
				for _, v := range td.Variants {
					writeDoc(&b, "\t", v.Doc)
					value := fmt.Sprintf("%q", v.Const)
					if strings.HasPrefix(td.Base, "int") || strings.HasPrefix(td.Base, "uint") {
						value = v.Const
					}
					fmt.Fprintf(&b, "\t%s%s %s = %s\n", td.Name, v.GoName, td.Name, value)
				}
				b.WriteString(")\n\n")
			}

		case kindStruct:
			emitStruct(&b, td)

		case kindAlias:
			fmt.Fprintf(&b, "type %s = %s\n\n", td.Name, td.Alias)

		case kindAny:
			fmt.Fprintf(&b, "type %s any\n\n", td.Name)

		case kindTaggedUnion:
			emitTaggedUnion(&b, r, td)

		case kindUntaggedUnion:
			emitUntaggedUnion(&b, r, td)
		}
	}
	return formatSrc(b.String())
}

func emitStruct(b *strings.Builder, td *typeDef) {
	fmt.Fprintf(b, "type %s struct {\n", td.Name)
	for _, f := range td.Fields {
		writeDoc(b, "\t", f.Doc)
		fmt.Fprintf(b, "\t%s\n", f.goDecl())
	}
	b.WriteString("}\n\n")
}

// payloadType renders the Go type of a union variant payload field.
func payloadType(r *ir, td *typeDef, v variant) string {
	switch {
	case v.Open:
		return td.Name + "Other"
	case v.Payload != "":
		return v.Payload
	default: // inline variant, possibly field-less
		return td.Name + v.GoName
	}
}

func emitTaggedUnion(b *strings.Builder, r *ir, td *typeDef) {
	kindType := td.Name + "Kind"
	shadow := unexport(td.Name) + "Shadow"

	fmt.Fprintf(b, "type %s string\n\n", kindType)
	b.WriteString("const (\n")
	for _, v := range td.Variants {
		if v.Const == "" {
			continue
		}
		fmt.Fprintf(b, "\t%s%s %s = %q\n", kindType, pascal(v.Const), kindType, v.Const)
	}
	b.WriteString(")\n\n")

	fmt.Fprintf(b, "// %s is a tagged union discriminated by %q.\n", td.Name, td.TagJSON)
	fmt.Fprintf(b, "// Exactly one variant pointer must be set. Kind is set on decode and\n// derived from the payload on encode; setting it by hand has no effect.\n")
	fmt.Fprintf(b, "type %s struct {\n", td.Name)
	fmt.Fprintf(b, "\tKind %s `json:\"-\"`\n", kindType)
	for _, f := range td.Fields {
		writeDoc(b, "\t", f.Doc)
		fmt.Fprintf(b, "\t%s\n", f.goDecl())
	}
	for _, v := range td.Variants {
		fmt.Fprintf(b, "\t%s *%s `json:\"-\"`\n", v.GoName, payloadType(r, td, v))
	}
	b.WriteString("}\n\n")

	// Open-variant payload: the raw wire object, preserved verbatim.
	for _, v := range td.Variants {
		if !v.Open {
			continue
		}
		fmt.Fprintf(b, "// %s preserves an unrecognized %s payload verbatim.\n", td.Name+"Other", td.Name)
		fmt.Fprintf(b, "type %sOther struct{ Raw json.RawMessage }\n\n", td.Name)
		fmt.Fprintf(b, "func (v %sOther) MarshalJSON() ([]byte, error) { return v.Raw, nil }\n\n", td.Name)
	}

	// Inline variant payload structs.
	for _, v := range td.Variants {
		if v.Open || v.Payload != "" {
			continue
		}
		fmt.Fprintf(b, "type %s%s struct {\n", td.Name, v.GoName)
		for _, f := range v.Inline {
			writeDoc(b, "\t", f.Doc)
			fmt.Fprintf(b, "\t%s\n", f.goDecl())
		}
		b.WriteString("}\n\n")
	}

	if len(td.Fields) > 0 {
		fmt.Fprintf(b, "// %s mirrors %s without its union methods, for encoding common fields.\ntype %s %s\n\n", shadow, td.Name, shadow, td.Name)
	}

	// Marshal: derive the tag from the set payload, merge common fields.
	fmt.Fprintf(b, "func (v %s) MarshalJSON() ([]byte, error) {\n", td.Name)
	fmt.Fprintf(b, "\tobj := map[string]json.RawMessage{}\n")
	if len(td.Fields) > 0 {
		fmt.Fprintf(b, "\tif common, err := json.Marshal(%s(v)); err != nil {\n\t\treturn nil, err\n\t} else if len(common) > 2 {\n\t\tif err := json.Unmarshal(common, &obj); err != nil {\n\t\t\treturn nil, err\n\t\t}\n\t}\n", shadow)
	}
	fmt.Fprintf(b, "\tset := 0\n")
	for _, v := range td.Variants {
		fmt.Fprintf(b, "\tif v.%s != nil {\n\t\tset++\n\t}\n", v.GoName)
	}
	fmt.Fprintf(b, "\tif set != 1 {\n\t\treturn nil, fmt.Errorf(\"%%s: exactly one variant must be set, have %%d\", \"%s\", set)\n\t}\n", td.Name)
	for _, v := range td.Variants {
		switch {
		case v.Open:
			fmt.Fprintf(b, "\tif v.Other != nil {\n\t\treturn v.Other.Raw, nil\n\t}\n")
		default:
			fmt.Fprintf(b, "\tif v.%s != nil {\n", v.GoName)
			if v.Const != "" {
				fmt.Fprintf(b, "\t\tif tag, err := json.Marshal(%q); err != nil {\n\t\t\treturn nil, err\n\t\t} else {\n\t\t\tobj[%q] = tag\n\t\t}\n", v.Const, td.TagJSON)
			}
			fmt.Fprintf(b, "\t\tpayload, err := json.Marshal(v.%s)\n\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n\t\tvar fields map[string]json.RawMessage\n\t\tif err := json.Unmarshal(payload, &fields); err != nil {\n\t\t\treturn nil, fmt.Errorf(\"%s payload: %%w\", err)\n\t\t}\n\t\tfor k, raw := range fields {\n\t\t\tobj[k] = raw\n\t\t}\n\t}\n", v.GoName, td.Name)
		}
	}
	fmt.Fprintf(b, "\treturn json.Marshal(obj)\n}\n\n")

	// Unmarshal: route on the wire tag; absent tag selects the default variant.
	fmt.Fprintf(b, "func (v *%s) UnmarshalJSON(data []byte) error {\n", td.Name)
	fmt.Fprintf(b, "\tvar raws map[string]json.RawMessage\n\tif err := json.Unmarshal(data, &raws); err != nil {\n\t\treturn err\n\t}\n\t*v = %s{}\n", td.Name)
	if len(td.Fields) > 0 {
		fmt.Fprintf(b, "\tif err := json.Unmarshal(data, (*%s)(v)); err != nil {\n\t\treturn err\n\t}\n", shadow)
	}
	fmt.Fprintf(b, "\tvar tag string\n\tif raw, ok := raws[%q]; ok {\n\t\tif err := json.Unmarshal(raw, &tag); err != nil {\n\t\t\treturn fmt.Errorf(\"%s tag: %%w\", err)\n\t\t}\n\t}\n\tswitch tag {\n", td.TagJSON, td.Name)
	for _, v := range td.Variants {
		switch {
		case v.Open:
			continue
		case v.Const != "":
			fmt.Fprintf(b, "\tcase %q:\n\t\tv.Kind = %s%s\n\t\tv.%s = new(%s)\n\t\treturn json.Unmarshal(data, v.%s)\n", v.Const, kindType, pascal(v.Const), v.GoName, payloadType(r, td, v), v.GoName)
		case v.Default:
			fmt.Fprintf(b, "\tcase \"\":\n\t\tv.%s = new(%s)\n\t\treturn json.Unmarshal(data, v.%s)\n", v.GoName, payloadType(r, td, v), v.GoName)
		}
	}
	if hasOpenVariant(td) {
		fmt.Fprintf(b, "\tdefault:\n\t\tv.Kind = %s(tag)\n\t\tv.Other = &%sOther{Raw: append(json.RawMessage(nil), data...)}\n\t\treturn nil\n\t}\n", kindType, td.Name)
	} else {
		fmt.Fprintf(b, "\tdefault:\n\t\treturn fmt.Errorf(\"%s: unknown %s tag %%q\", tag)\n\t}\n", td.Name, td.TagJSON)
	}
	fmt.Fprintf(b, "}\n\n")
}

func hasOpenVariant(td *typeDef) bool {
	for _, v := range td.Variants {
		if v.Open {
			return true
		}
	}
	return false
}

func emitUntaggedUnion(b *strings.Builder, r *ir, td *typeDef) {
	shadow := unexport(td.Name) + "Shadow"

	fmt.Fprintf(b, "// %s is a shape-disambiguated union. Exactly one variant pointer must be\n// set; decoding probes each variant's required wire keys in order.\n", td.Name)
	fmt.Fprintf(b, "type %s struct {\n", td.Name)
	for _, f := range td.Fields {
		writeDoc(b, "\t", f.Doc)
		fmt.Fprintf(b, "\t%s\n", f.goDecl())
	}
	for _, v := range td.Variants {
		fmt.Fprintf(b, "\t%s *%s `json:\"-\"`\n", v.GoName, v.Payload)
	}
	b.WriteString("}\n\n")

	if len(td.Fields) > 0 {
		fmt.Fprintf(b, "// %s mirrors %s without its union methods, for encoding common fields.\ntype %s %s\n\n", shadow, td.Name, shadow, td.Name)
	}

	fmt.Fprintf(b, "func (v %s) MarshalJSON() ([]byte, error) {\n", td.Name)
	fmt.Fprintf(b, "\tobj := map[string]json.RawMessage{}\n")
	if len(td.Fields) > 0 {
		fmt.Fprintf(b, "\tif common, err := json.Marshal(%s(v)); err != nil {\n\t\treturn nil, err\n\t} else if len(common) > 2 {\n\t\tif err := json.Unmarshal(common, &obj); err != nil {\n\t\t\treturn nil, err\n\t\t}\n\t}\n", shadow)
	}
	fmt.Fprintf(b, "\tset := 0\n")
	for _, v := range td.Variants {
		fmt.Fprintf(b, "\tif v.%s != nil {\n\t\tset++\n\t}\n", v.GoName)
	}
	fmt.Fprintf(b, "\tif set != 1 {\n\t\treturn nil, fmt.Errorf(\"%%s: exactly one variant must be set, have %%d\", \"%s\", set)\n\t}\n", td.Name)
	for _, v := range td.Variants {
		fmt.Fprintf(b, "\tif v.%s != nil {\n\t\tpayload, err := json.Marshal(v.%s)\n\t\tif err != nil {\n\t\treturn nil, err\n\t\t}\n", v.GoName, v.GoName)
		if strings.HasPrefix(v.Payload, "[]") {
			fmt.Fprintf(b, "\t\treturn payload, nil\n\t}\n")
		} else {
			fmt.Fprintf(b, "\t\tvar fields map[string]json.RawMessage\n\t\tif err := json.Unmarshal(payload, &fields); err != nil {\n\t\t\treturn nil, fmt.Errorf(\"%s payload: %%w\", err)\n\t\t}\n\t\tfor k, raw := range fields {\n\t\t\tobj[k] = raw\n\t\t}\n\t}\n", td.Name)
		}
	}
	fmt.Fprintf(b, "\treturn json.Marshal(obj)\n}\n\n")

	fmt.Fprintf(b, "func (v *%s) UnmarshalJSON(data []byte) error {\n", td.Name)
	fmt.Fprintf(b, "\t*v = %s{}\n", td.Name)
	if len(td.Fields) > 0 {
		fmt.Fprintf(b, "\tif err := json.Unmarshal(data, (*%s)(v)); err != nil {\n\t\treturn err\n\t}\n", shadow)
	}
	for i, v := range td.Variants {
		keyword := "if"
		if i > 0 {
			keyword = "} else if"
		}
		fmt.Fprintf(b, "\t%s %s {\n\t\tv.%s = new(%s)\n\t\treturn json.Unmarshal(data, v.%s)\n\t", keyword, probeCall(r, v.Payload), v.GoName, v.Payload, v.GoName)
	}
	fmt.Fprintf(b, "}\n\treturn fmt.Errorf(\"%s: payload matches no variant\")\n}\n\n", td.Name)

	// Probe helpers are shared across unions; emit once.
	if !probeHelpersEmitted {
		probeHelpersEmitted = true
		b.WriteString(`
func hasKeys(data []byte, keys ...string) bool {
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return false
	}
	for _, k := range keys {
		if _, ok := obj[k]; !ok {
			return false
		}
	}
	return true
}

func arrayHasKeys(data []byte, keys ...string) bool {
	var items []json.RawMessage
	if err := json.Unmarshal(data, &items); err != nil {
		return false
	}
	if len(items) == 0 {
		return true // an empty array fits the first variant
	}
	return hasKeys(items[0], keys...)
}

`)
	}
}

var probeHelpersEmitted bool

// requiredKeysExpr lists the payload def's required wire keys for probing.
func requiredKeysExpr(r *ir, defName string) []string {
	td := r.ByName[defName]
	if td == nil {
		return nil
	}
	var keys []string
	for _, f := range td.Fields {
		if f.Required {
			keys = append(keys, f.JSONName)
		}
	}
	return keys
}

// probeCall renders the shape test guarding one untagged variant. Array
// variants probe their first element against the item def's required keys.
func probeCall(r *ir, payload string) string {
	if item := strings.TrimPrefix(payload, "[]"); item != payload {
		keys := requiredKeysExpr(r, item)
		return fmt.Sprintf("arrayHasKeys(data, %s)", quoteList(keys))
	}
	keys := requiredKeysExpr(r, payload)
	if len(keys) == 0 {
		// No required keys to disambiguate: accept only in listed order.
		return "true"
	}
	return fmt.Sprintf("hasKeys(data, %s)", quoteList(keys))
}

func quoteList(items []string) string {
	parts := make([]string, len(items))
	for i, s := range items {
		parts[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(parts, ", ")
}

func unexport(name string) string {
	if name == "" {
		return name
	}
	return strings.ToLower(name[:1]) + name[1:]
}

func emitMethods(r *ir, pin, packageName string) []byte {
	var b strings.Builder
	b.WriteString(header(pin, "method registry"))
	b.WriteString("package " + packageName + "\n\nimport \"reflect\"\n\n")

	b.WriteString("// Sides classify which peer owns a method's API surface.\nconst (\n")
	b.WriteString("\tSideAgent = \"agent\"    // requests are served by the agent\n")
	b.WriteString("\tSideClient = \"client\"   // requests are served by the client\n")
	b.WriteString("\tSideProtocol = \"protocol\" // connection-level notifications\n")
	b.WriteString("\tSideBoth = \"both\" // either peer may send the request or notification\n")
	b.WriteString(")\n\n")

	b.WriteString("const (\n")
	for _, m := range r.Methods {
		fmt.Fprintf(&b, "\t%sMethodName = %q\n", m.GoName, m.Name)
	}
	b.WriteString(")\n\n")

	b.WriteString(`// Method describes one ACP wire method: its name, owning side, the schema
// types of its parameters and result, and whether it is a notification.
type Method struct {
	Name                string
	Side                string
	Params              reflect.Type // nil when the method takes no typed request params
	NotificationParams  reflect.Type // distinct notification params for bidirectional methods
	Result              reflect.Type // nil for notifications and empty results
	Notification        bool
}

// Methods indexes every method in the pinned schema release by wire name.
var Methods = map[string]Method{
`)
	for _, m := range r.Methods {
		fmt.Fprintf(&b, "\t%q: {Name: %q, Side: %s", m.Name, m.Name, sideConst(m.Side))
		if m.Params != "" {
			fmt.Fprintf(&b, ", Params: reflect.TypeOf(&%s{}).Elem()", m.Params)
		}
		if m.NotificationParams != "" && m.NotificationParams != m.Params {
			fmt.Fprintf(&b, ", NotificationParams: reflect.TypeOf(&%s{}).Elem()", m.NotificationParams)
		}
		if m.Result != "" {
			fmt.Fprintf(&b, ", Result: reflect.TypeOf(&%s{}).Elem()", m.Result)
		}
		if m.Notification {
			fmt.Fprintf(&b, ", Notification: true")
		}
		fmt.Fprintf(&b, "},\n")
	}
	b.WriteString("}\n")
	return formatSrc(b.String())
}

func sideConst(side string) string {
	switch side {
	case "agent":
		return "SideAgent"
	case "client":
		return "SideClient"
	case "both":
		return "SideBoth"
	default:
		return "SideProtocol"
	}
}

func emitParity(r *ir, pin, packageName string) []byte {
	var b strings.Builder
	b.WriteString(header(pin, "round-trip parity fixtures"))
	b.WriteString("package " + packageName + "\n\nimport \"reflect\"\n\n")
	b.WriteString("var parityCases = []parityCase{\n")
	for _, td := range r.Defs {
		switch td.Kind {
		case kindStruct, kindTaggedUnion, kindUntaggedUnion, kindNewtype, kindEnum, kindAny, kindAlias:
		default:
			continue
		}
		minimal, err := synthWire(r, td.Name, false, map[string]int{})
		if err != nil {
			panic(fmt.Sprintf("synthesize minimal %s: %v", td.Name, err))
		}
		full, err := synthWire(r, td.Name, true, map[string]int{})
		if err != nil {
			panic(fmt.Sprintf("synthesize full %s: %v", td.Name, err))
		}
		fmt.Fprintf(&b, "\t{name: %q, typ: reflect.TypeOf(new(%s)).Elem(), minimal: `%s`, full: `%s`},\n", td.Name, td.Name, minimal, full)
	}
	b.WriteString("}\n")
	return formatSrc(b.String())
}
