// Code generated by acpgen from ACP JSON Schema release schema-v2.0.0-alpha.3 (method registry). DO NOT EDIT.

package v2

import "reflect"

// Sides classify which peer owns a method's API surface.
const (
	SideAgent    = "agent"    // requests are served by the agent
	SideClient   = "client"   // requests are served by the client
	SideProtocol = "protocol" // connection-level notifications
)

const (
	CancelRequestMethodName            = "$/cancel_request"
	AuthLoginMethodName                = "auth/login"
	AuthLogoutMethodName               = "auth/logout"
	ElicitationCompleteMethodName      = "elicitation/complete"
	ElicitationCreateMethodName        = "elicitation/create"
	InitializeMethodName               = "initialize"
	SessionCancelMethodName            = "session/cancel"
	SessionCloseMethodName             = "session/close"
	SessionDeleteMethodName            = "session/delete"
	SessionListMethodName              = "session/list"
	SessionNewMethodName               = "session/new"
	SessionPromptMethodName            = "session/prompt"
	SessionRequestPermissionMethodName = "session/request_permission"
	SessionResumeMethodName            = "session/resume"
	SessionSetConfigOptionMethodName   = "session/set_config_option"
	SessionUpdateMethodName            = "session/update"
)

// Method describes one ACP wire method: its name, owning side, the schema
// types of its parameters and result, and whether it is a notification.
type Method struct {
	Name         string
	Side         string
	Params       reflect.Type // nil when the method takes no typed params
	Result       reflect.Type // nil for notifications and empty results
	Notification bool
}

// Methods indexes every method in the pinned schema release by wire name.
var Methods = map[string]Method{
	"$/cancel_request":           {Name: "$/cancel_request", Side: SideProtocol, Params: reflect.TypeOf(&CancelRequestNotification{}).Elem(), Notification: true},
	"auth/login":                 {Name: "auth/login", Side: SideAgent, Params: reflect.TypeOf(&LoginAuthRequest{}).Elem(), Result: reflect.TypeOf(&LoginAuthResponse{}).Elem()},
	"auth/logout":                {Name: "auth/logout", Side: SideAgent, Params: reflect.TypeOf(&LogoutAuthRequest{}).Elem(), Result: reflect.TypeOf(&LogoutAuthResponse{}).Elem()},
	"elicitation/complete":       {Name: "elicitation/complete", Side: SideClient, Params: reflect.TypeOf(&CompleteElicitationNotification{}).Elem(), Notification: true},
	"elicitation/create":         {Name: "elicitation/create", Side: SideClient, Params: reflect.TypeOf(&CreateElicitationRequest{}).Elem(), Result: reflect.TypeOf(&CreateElicitationResponse{}).Elem()},
	"initialize":                 {Name: "initialize", Side: SideAgent, Params: reflect.TypeOf(&InitializeRequest{}).Elem(), Result: reflect.TypeOf(&InitializeResponse{}).Elem()},
	"session/cancel":             {Name: "session/cancel", Side: SideAgent, Params: reflect.TypeOf(&CancelSessionNotification{}).Elem(), Notification: true},
	"session/close":              {Name: "session/close", Side: SideAgent, Params: reflect.TypeOf(&CloseSessionRequest{}).Elem(), Result: reflect.TypeOf(&CloseSessionResponse{}).Elem()},
	"session/delete":             {Name: "session/delete", Side: SideAgent, Params: reflect.TypeOf(&DeleteSessionRequest{}).Elem(), Result: reflect.TypeOf(&DeleteSessionResponse{}).Elem()},
	"session/list":               {Name: "session/list", Side: SideAgent, Params: reflect.TypeOf(&ListSessionsRequest{}).Elem(), Result: reflect.TypeOf(&ListSessionsResponse{}).Elem()},
	"session/new":                {Name: "session/new", Side: SideAgent, Params: reflect.TypeOf(&NewSessionRequest{}).Elem(), Result: reflect.TypeOf(&NewSessionResponse{}).Elem()},
	"session/prompt":             {Name: "session/prompt", Side: SideAgent, Params: reflect.TypeOf(&PromptRequest{}).Elem(), Result: reflect.TypeOf(&PromptResponse{}).Elem()},
	"session/request_permission": {Name: "session/request_permission", Side: SideClient, Params: reflect.TypeOf(&RequestPermissionRequest{}).Elem(), Result: reflect.TypeOf(&RequestPermissionResponse{}).Elem()},
	"session/resume":             {Name: "session/resume", Side: SideAgent, Params: reflect.TypeOf(&ResumeSessionRequest{}).Elem(), Result: reflect.TypeOf(&ResumeSessionResponse{}).Elem()},
	"session/set_config_option":  {Name: "session/set_config_option", Side: SideAgent, Params: reflect.TypeOf(&SetSessionConfigOptionRequest{}).Elem(), Result: reflect.TypeOf(&SetSessionConfigOptionResponse{}).Elem()},
	"session/update":             {Name: "session/update", Side: SideClient, Params: reflect.TypeOf(&UpdateSessionNotification{}).Elem(), Notification: true},
}
