// Code generated by acpgen from ACP JSON Schema release schema-v2.0.0-alpha.3-unstable (method registry). DO NOT EDIT.

package unstable

import "reflect"

// Sides classify which peer owns a method's API surface.
const (
	SideAgent    = "agent"    // requests are served by the agent
	SideClient   = "client"   // requests are served by the client
	SideProtocol = "protocol" // connection-level notifications
	SideBoth     = "both"     // either peer may send the request or notification
)

const (
	CancelRequestMethodName            = "$/cancel_request"
	AuthLoginMethodName                = "auth/login"
	AuthLogoutMethodName               = "auth/logout"
	DocumentDidchangeMethodName        = "document/didChange"
	DocumentDidcloseMethodName         = "document/didClose"
	DocumentDidfocusMethodName         = "document/didFocus"
	DocumentDidopenMethodName          = "document/didOpen"
	DocumentDidsaveMethodName          = "document/didSave"
	ElicitationCompleteMethodName      = "elicitation/complete"
	ElicitationCreateMethodName        = "elicitation/create"
	InitializeMethodName               = "initialize"
	McpConnectMethodName               = "mcp/connect"
	McpDisconnectMethodName            = "mcp/disconnect"
	McpMessageMethodName               = "mcp/message"
	NesAcceptMethodName                = "nes/accept"
	NesCloseMethodName                 = "nes/close"
	NesRejectMethodName                = "nes/reject"
	NesStartMethodName                 = "nes/start"
	NesSuggestMethodName               = "nes/suggest"
	ProvidersDisableMethodName         = "providers/disable"
	ProvidersListMethodName            = "providers/list"
	ProvidersSetMethodName             = "providers/set"
	SessionCancelMethodName            = "session/cancel"
	SessionCloseMethodName             = "session/close"
	SessionDeleteMethodName            = "session/delete"
	SessionForkMethodName              = "session/fork"
	SessionListMethodName              = "session/list"
	SessionNewMethodName               = "session/new"
	SessionPromptMethodName            = "session/prompt"
	SessionRequestPermissionMethodName = "session/request_permission"
	SessionResumeMethodName            = "session/resume"
	SessionSetConfigOptionMethodName   = "session/set_config_option"
	SessionUpdateMethodName            = "session/update"
)

// Method describes one ACP wire method: its name, owning side, the schema
// types of its parameters and result, and whether it is a notification.
type Method struct {
	Name               string
	Side               string
	Params             reflect.Type // nil when the method takes no typed request params
	NotificationParams reflect.Type // distinct notification params for bidirectional methods
	Result             reflect.Type // nil for notifications and empty results
	Notification       bool
}

// Methods indexes every method in the pinned schema release by wire name.
var Methods = map[string]Method{
	"$/cancel_request":           {Name: "$/cancel_request", Side: SideProtocol, Params: reflect.TypeOf(&CancelRequestNotification{}).Elem(), Notification: true},
	"auth/login":                 {Name: "auth/login", Side: SideAgent, Params: reflect.TypeOf(&LoginAuthRequest{}).Elem(), Result: reflect.TypeOf(&LoginAuthResponse{}).Elem()},
	"auth/logout":                {Name: "auth/logout", Side: SideAgent, Params: reflect.TypeOf(&LogoutAuthRequest{}).Elem(), Result: reflect.TypeOf(&LogoutAuthResponse{}).Elem()},
	"document/didChange":         {Name: "document/didChange", Side: SideAgent, Params: reflect.TypeOf(&DidChangeDocumentNotification{}).Elem(), Notification: true},
	"document/didClose":          {Name: "document/didClose", Side: SideAgent, Params: reflect.TypeOf(&DidCloseDocumentNotification{}).Elem(), Notification: true},
	"document/didFocus":          {Name: "document/didFocus", Side: SideAgent, Params: reflect.TypeOf(&DidFocusDocumentNotification{}).Elem(), Notification: true},
	"document/didOpen":           {Name: "document/didOpen", Side: SideAgent, Params: reflect.TypeOf(&DidOpenDocumentNotification{}).Elem(), Notification: true},
	"document/didSave":           {Name: "document/didSave", Side: SideAgent, Params: reflect.TypeOf(&DidSaveDocumentNotification{}).Elem(), Notification: true},
	"elicitation/complete":       {Name: "elicitation/complete", Side: SideClient, Params: reflect.TypeOf(&CompleteElicitationNotification{}).Elem(), Notification: true},
	"elicitation/create":         {Name: "elicitation/create", Side: SideClient, Params: reflect.TypeOf(&CreateElicitationRequest{}).Elem(), Result: reflect.TypeOf(&CreateElicitationResponse{}).Elem()},
	"initialize":                 {Name: "initialize", Side: SideAgent, Params: reflect.TypeOf(&InitializeRequest{}).Elem(), Result: reflect.TypeOf(&InitializeResponse{}).Elem()},
	"mcp/connect":                {Name: "mcp/connect", Side: SideClient, Params: reflect.TypeOf(&ConnectMcpRequest{}).Elem(), Result: reflect.TypeOf(&ConnectMcpResponse{}).Elem()},
	"mcp/disconnect":             {Name: "mcp/disconnect", Side: SideClient, Params: reflect.TypeOf(&DisconnectMcpRequest{}).Elem(), Result: reflect.TypeOf(&DisconnectMcpResponse{}).Elem()},
	"mcp/message":                {Name: "mcp/message", Side: SideBoth, Params: reflect.TypeOf(&MessageMcpRequest{}).Elem(), NotificationParams: reflect.TypeOf(&MessageMcpNotification{}).Elem(), Result: reflect.TypeOf(&MessageMcpResponse{}).Elem(), Notification: true},
	"nes/accept":                 {Name: "nes/accept", Side: SideAgent, Params: reflect.TypeOf(&AcceptNesNotification{}).Elem(), Notification: true},
	"nes/close":                  {Name: "nes/close", Side: SideAgent, Params: reflect.TypeOf(&CloseNesRequest{}).Elem(), Result: reflect.TypeOf(&CloseNesResponse{}).Elem()},
	"nes/reject":                 {Name: "nes/reject", Side: SideAgent, Params: reflect.TypeOf(&RejectNesNotification{}).Elem(), Notification: true},
	"nes/start":                  {Name: "nes/start", Side: SideAgent, Params: reflect.TypeOf(&StartNesRequest{}).Elem(), Result: reflect.TypeOf(&StartNesResponse{}).Elem()},
	"nes/suggest":                {Name: "nes/suggest", Side: SideAgent, Params: reflect.TypeOf(&SuggestNesRequest{}).Elem(), Result: reflect.TypeOf(&SuggestNesResponse{}).Elem()},
	"providers/disable":          {Name: "providers/disable", Side: SideAgent, Params: reflect.TypeOf(&DisableProviderRequest{}).Elem(), Result: reflect.TypeOf(&DisableProviderResponse{}).Elem()},
	"providers/list":             {Name: "providers/list", Side: SideAgent, Params: reflect.TypeOf(&ListProvidersRequest{}).Elem(), Result: reflect.TypeOf(&ListProvidersResponse{}).Elem()},
	"providers/set":              {Name: "providers/set", Side: SideAgent, Params: reflect.TypeOf(&SetProviderRequest{}).Elem(), Result: reflect.TypeOf(&SetProviderResponse{}).Elem()},
	"session/cancel":             {Name: "session/cancel", Side: SideAgent, Params: reflect.TypeOf(&CancelSessionNotification{}).Elem(), Notification: true},
	"session/close":              {Name: "session/close", Side: SideAgent, Params: reflect.TypeOf(&CloseSessionRequest{}).Elem(), Result: reflect.TypeOf(&CloseSessionResponse{}).Elem()},
	"session/delete":             {Name: "session/delete", Side: SideAgent, Params: reflect.TypeOf(&DeleteSessionRequest{}).Elem(), Result: reflect.TypeOf(&DeleteSessionResponse{}).Elem()},
	"session/fork":               {Name: "session/fork", Side: SideAgent, Params: reflect.TypeOf(&ForkSessionRequest{}).Elem(), Result: reflect.TypeOf(&ForkSessionResponse{}).Elem()},
	"session/list":               {Name: "session/list", Side: SideAgent, Params: reflect.TypeOf(&ListSessionsRequest{}).Elem(), Result: reflect.TypeOf(&ListSessionsResponse{}).Elem()},
	"session/new":                {Name: "session/new", Side: SideAgent, Params: reflect.TypeOf(&NewSessionRequest{}).Elem(), Result: reflect.TypeOf(&NewSessionResponse{}).Elem()},
	"session/prompt":             {Name: "session/prompt", Side: SideAgent, Params: reflect.TypeOf(&PromptRequest{}).Elem(), Result: reflect.TypeOf(&PromptResponse{}).Elem()},
	"session/request_permission": {Name: "session/request_permission", Side: SideClient, Params: reflect.TypeOf(&RequestPermissionRequest{}).Elem(), Result: reflect.TypeOf(&RequestPermissionResponse{}).Elem()},
	"session/resume":             {Name: "session/resume", Side: SideAgent, Params: reflect.TypeOf(&ResumeSessionRequest{}).Elem(), Result: reflect.TypeOf(&ResumeSessionResponse{}).Elem()},
	"session/set_config_option":  {Name: "session/set_config_option", Side: SideAgent, Params: reflect.TypeOf(&SetSessionConfigOptionRequest{}).Elem(), Result: reflect.TypeOf(&SetSessionConfigOptionResponse{}).Elem()},
	"session/update":             {Name: "session/update", Side: SideClient, Params: reflect.TypeOf(&UpdateSessionNotification{}).Elem(), Notification: true},
}
