// Code generated by acpgen from ACP JSON Schema release schema-v1.21.0 (method registry). DO NOT EDIT.

package schema

import "reflect"

// Sides classify which peer owns a method's API surface.
const (
	SideAgent    = "agent"    // requests are served by the agent
	SideClient   = "client"   // requests are served by the client
	SideProtocol = "protocol" // connection-level notifications
)

const (
	CancelRequestMethodName            = "$/cancel_request"
	AuthenticateMethodName             = "authenticate"
	ElicitationCompleteMethodName      = "elicitation/complete"
	ElicitationCreateMethodName        = "elicitation/create"
	FsReadTextFileMethodName           = "fs/read_text_file"
	FsWriteTextFileMethodName          = "fs/write_text_file"
	InitializeMethodName               = "initialize"
	LogoutMethodName                   = "logout"
	SessionCancelMethodName            = "session/cancel"
	SessionCloseMethodName             = "session/close"
	SessionDeleteMethodName            = "session/delete"
	SessionListMethodName              = "session/list"
	SessionLoadMethodName              = "session/load"
	SessionNewMethodName               = "session/new"
	SessionPromptMethodName            = "session/prompt"
	SessionRequestPermissionMethodName = "session/request_permission"
	SessionResumeMethodName            = "session/resume"
	SessionSetConfigOptionMethodName   = "session/set_config_option"
	SessionSetModeMethodName           = "session/set_mode"
	SessionUpdateMethodName            = "session/update"
	TerminalCreateMethodName           = "terminal/create"
	TerminalKillMethodName             = "terminal/kill"
	TerminalOutputMethodName           = "terminal/output"
	TerminalReleaseMethodName          = "terminal/release"
	TerminalWaitForExitMethodName      = "terminal/wait_for_exit"
)

// Method describes one ACP wire method: its name, owning side, the schema
// types of its parameters and result, and whether it is a notification.
type Method struct {
	Name         string
	Side         string
	Params       reflect.Type // nil when the method takes no typed params
	Result       reflect.Type // nil for notifications and empty results
	Notification bool
}

// Methods indexes every method in the pinned schema release by wire name.
var Methods = map[string]Method{
	"$/cancel_request":           {Name: "$/cancel_request", Side: SideProtocol, Params: reflect.TypeOf(&CancelRequestNotification{}).Elem(), Notification: true},
	"authenticate":               {Name: "authenticate", Side: SideAgent, Params: reflect.TypeOf(&AuthenticateRequest{}).Elem(), Result: reflect.TypeOf(&AuthenticateResponse{}).Elem()},
	"elicitation/complete":       {Name: "elicitation/complete", Side: SideClient, Params: reflect.TypeOf(&CompleteElicitationNotification{}).Elem(), Notification: true},
	"elicitation/create":         {Name: "elicitation/create", Side: SideClient, Params: reflect.TypeOf(&CreateElicitationRequest{}).Elem(), Result: reflect.TypeOf(&CreateElicitationResponse{}).Elem()},
	"fs/read_text_file":          {Name: "fs/read_text_file", Side: SideClient, Params: reflect.TypeOf(&ReadTextFileRequest{}).Elem(), Result: reflect.TypeOf(&ReadTextFileResponse{}).Elem()},
	"fs/write_text_file":         {Name: "fs/write_text_file", Side: SideClient, Params: reflect.TypeOf(&WriteTextFileRequest{}).Elem(), Result: reflect.TypeOf(&WriteTextFileResponse{}).Elem()},
	"initialize":                 {Name: "initialize", Side: SideAgent, Params: reflect.TypeOf(&InitializeRequest{}).Elem(), Result: reflect.TypeOf(&InitializeResponse{}).Elem()},
	"logout":                     {Name: "logout", Side: SideAgent, Params: reflect.TypeOf(&LogoutRequest{}).Elem(), Result: reflect.TypeOf(&LogoutResponse{}).Elem()},
	"session/cancel":             {Name: "session/cancel", Side: SideAgent, Params: reflect.TypeOf(&CancelNotification{}).Elem(), Notification: true},
	"session/close":              {Name: "session/close", Side: SideAgent, Params: reflect.TypeOf(&CloseSessionRequest{}).Elem(), Result: reflect.TypeOf(&CloseSessionResponse{}).Elem()},
	"session/delete":             {Name: "session/delete", Side: SideAgent, Params: reflect.TypeOf(&DeleteSessionRequest{}).Elem(), Result: reflect.TypeOf(&DeleteSessionResponse{}).Elem()},
	"session/list":               {Name: "session/list", Side: SideAgent, Params: reflect.TypeOf(&ListSessionsRequest{}).Elem(), Result: reflect.TypeOf(&ListSessionsResponse{}).Elem()},
	"session/load":               {Name: "session/load", Side: SideAgent, Params: reflect.TypeOf(&LoadSessionRequest{}).Elem(), Result: reflect.TypeOf(&LoadSessionResponse{}).Elem()},
	"session/new":                {Name: "session/new", Side: SideAgent, Params: reflect.TypeOf(&NewSessionRequest{}).Elem(), Result: reflect.TypeOf(&NewSessionResponse{}).Elem()},
	"session/prompt":             {Name: "session/prompt", Side: SideAgent, Params: reflect.TypeOf(&PromptRequest{}).Elem(), Result: reflect.TypeOf(&PromptResponse{}).Elem()},
	"session/request_permission": {Name: "session/request_permission", Side: SideClient, Params: reflect.TypeOf(&RequestPermissionRequest{}).Elem(), Result: reflect.TypeOf(&RequestPermissionResponse{}).Elem()},
	"session/resume":             {Name: "session/resume", Side: SideAgent, Params: reflect.TypeOf(&ResumeSessionRequest{}).Elem(), Result: reflect.TypeOf(&ResumeSessionResponse{}).Elem()},
	"session/set_config_option":  {Name: "session/set_config_option", Side: SideAgent, Params: reflect.TypeOf(&SetSessionConfigOptionRequest{}).Elem(), Result: reflect.TypeOf(&SetSessionConfigOptionResponse{}).Elem()},
	"session/set_mode":           {Name: "session/set_mode", Side: SideAgent, Params: reflect.TypeOf(&SetSessionModeRequest{}).Elem(), Result: reflect.TypeOf(&SetSessionModeResponse{}).Elem()},
	"session/update":             {Name: "session/update", Side: SideClient, Params: reflect.TypeOf(&SessionNotification{}).Elem(), Notification: true},
	"terminal/create":            {Name: "terminal/create", Side: SideClient, Params: reflect.TypeOf(&CreateTerminalRequest{}).Elem(), Result: reflect.TypeOf(&CreateTerminalResponse{}).Elem()},
	"terminal/kill":              {Name: "terminal/kill", Side: SideClient, Params: reflect.TypeOf(&KillTerminalRequest{}).Elem(), Result: reflect.TypeOf(&KillTerminalResponse{}).Elem()},
	"terminal/output":            {Name: "terminal/output", Side: SideClient, Params: reflect.TypeOf(&TerminalOutputRequest{}).Elem(), Result: reflect.TypeOf(&TerminalOutputResponse{}).Elem()},
	"terminal/release":           {Name: "terminal/release", Side: SideClient, Params: reflect.TypeOf(&ReleaseTerminalRequest{}).Elem(), Result: reflect.TypeOf(&ReleaseTerminalResponse{}).Elem()},
	"terminal/wait_for_exit":     {Name: "terminal/wait_for_exit", Side: SideClient, Params: reflect.TypeOf(&WaitForTerminalExitRequest{}).Elem(), Result: reflect.TypeOf(&WaitForTerminalExitResponse{}).Elem()},
}
